spring:
    application:
        name: Task-Manager
    data:
        mongodb:
            uri: mongoUrl
            auto-index-creation: true
            connection-pool:
                max-size: 50
                min-size: 5
                max-wait-time: 2000
    redis:
        host: redisUrl
        port: 10808
        password: AhNt8x9Mme9sPiEZD1Hhau9w7iIKXsWV
    mail:
        host: smtp.gmail.com
        port: 587
        username: username
        password: taze fpqc ubfc zixu
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
    lifecycle:
        timeout-per-shutdown-phase: 30s

server:
    port: 8080
    shutdown: graceful

jwt:
    secret-key: secretKey
    expiration: 86400000 # 24 hours in milliseconds

app:
    base-url: http://localhost:8080
    frontend-url: http://localhost:3000
